### ISSUE TITLE
go get github.com/derekparker/delve/cmd/dlv fails with an error

### ISSUE THREAD

**Issue by ashvin-bhuttoo** [derekparker/delve#456]
When i do 'go get -v -u github.com/derekparker/delve/cmd/dlv' it fails with the following error (see bold):

github.com\derekparker\delve (download)
github.com/derekparker/delve/proc
**..\..\proc\disasm.go:9: undefined: ArchInst**

I am running windows 7 x64 and using go1.6, how do i fix it ?

**Comment by lukehoban** [comment]
It sounds like you must have a 32bit Go tool chain installed. Delve doesn't build for 32bit architectures currently. What is your `go env`?  If you set GOARCH to `amd64` can you successfully build?

That said, it would be nice if the `go get` failure were somehow clearer about what was wrong here.

**Comment by ashvin-bhuttoo** [comment]
You are right, i have 32bit Go installed, i'll try with 64bit

**go env output:**
set GOARCH=386
set GOBIN=C:\Go\bin\
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Go\
set GORACE=
set GOROOT=c:\go
set GOTOOLDIR=c:\go\pkg\tool\windows_386
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

**Comment by ashvin-bhuttoo** [comment]
Just installed 64bit Go and the following packages

github.com/golang/lint/golint
github.com/peterh/liner 
github.com/derekparker/delve/cmd/dlv

Debugging works fine in Visual Studio Code when i run it as administrator.

**Comment by Davidrjx** [comment]
Go1.11.2 make install output like
```
Error executing go [list -mod=vendor ./...]
2020/10/12 15:40:10 exit status 1
exit status 1
make: *** [Makefile:10: install] Error 1
```

**Comment by chainhelen** [comment]
@Davidrjx  Release 1.x.0 of delve will be tested against go 1.1x, 1.1(x-1) and 1.1(x-2). So 1.5.0 of dlv is guaranteed to build on 1.15, 1.14 and 1.13 of golang.  And the error you referred looks irrelevant to this issue.

**Comment by Davidrjx** [comment]
@chainhelen Got it, thanks.
