### ISSUE TITLE
CANT COMPILE 

### ISSUE THREAD

**Issue by MrLiet** [derekparker/delve#670]
Hello.

I have compile error:

![image](https://cloud.githubusercontent.com/assets/23429917/20272702/4ff18ac6-aac1-11e6-9e7b-215ac472d93c.png)

Source code:

```
package main

import "github.com/go-gl/glfw/v3.2/glfw"
import "runtime"

func main() {

	runtime.LockOSThread()

	glfw.Init()

	w, _ := glfw.CreateWindow(800, 600, "hello", nil, nil)

	for {
		glfw.PollEvents()
		if w.ShouldClose() {
			break
		}
	}

}
```

Console output:

> me/proj1
> github.com/go-gl/glfw/v3.2/glfw(.text): strdup: not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): strdup: not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): strdup: not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): strdup: not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: strdup
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: strdup
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: strdup
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: strdup
> exit status 2
> 

Im use:

- Windows 64 bit
- Go 1.7.3 
- Mingw 64
- VS Code

VS Code settings:
```
{
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.buildTags": "",
    "go.buildFlags": [],
    "go.lintTool": "golint",
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.coverOnSave":false,
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.formatOnSave": true, 
    "go.formatTool": "goreturns",
    "go.formatFlags": [],
    "go.gocodeAutoBuild": false,
    "go.autocompleteUnimportedPackages": true
}
```

and Launch settings:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceRoot}",
            "env": {},
            "args": []
        }
    ]
}
```

And it's work fine with glfw 3.1 version
![image](https://cloud.githubusercontent.com/assets/23429917/20272758/7aef4be6-aac1-11e6-8d41-a8a5081817a6.png)

GLFW supports says: 

> You're probably using an old version of Go.

Seems like delve use for debug old version of Go. How i can fix it ?

**Comment by aarzilli** [comment]
The VSCode plugin is maintained [here](https://github.com/Microsoft/vscode-go). Dlv itself just uses whatever go happens to be in the path.

**Comment by alexbrainman** [comment]
The problem is that your program fails to build, if you use "internal" linker. Just run:
```
go build -ldflags="-linkmode=internal"
```
to see that for yourself.

By default, Go uses "external" linker, so when you run:
```
go build
```
everything just builds. But, delve, when building program before debugging it, forces use of "internal" linker, therefore you see what you see.

Alex

**Comment by MrLiet** [comment]
@alexbrainman @aarzilli  Thx for answer!

Im  changed build flags :
```
    "version": "0.2.0",
    
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "program": "${workspaceRoot}",
            **"buildFlags": "-ldflags '-linkmode=external'",**
            "env": {},
            "args": []
        }
        
```
and console output now:

> C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
> C:\Users\User\AppData\Local\Temp\go-link-502546875\go.o: file not recognized: File format not recognized
> collect2.exe: error: ld returned 1 exit status
>

**Comment by aarzilli** [comment]
Known bug: #631

**Comment by MrLiet** [comment]
@aarzilli  I.e. currently its cant fix ?

**Comment by aarzilli** [comment]
Yes.
