### ISSUE TITLE
Doesn't build on armhf

### ISSUE THREAD

**Issue by sokoow** [derekparker/delve#328]
Getting following when trying to build on armhf with go 1.5.1:

go test  -ldflags="-X main.Build=1a4250fb5147a9a06f608a5e89dccc4f62fd20c5" github.com/derekparker/delve/cmd/dlv github.com/derekparker/delve/config github.com/derekparker/delve/dwarf/frame github.com/derekparker/delve/dwarf/line github.com/derekparker/delve/dwarf/op github.com/derekparker/delve/dwarf/reader github.com/derekparker/delve/dwarf/util github.com/derekparker/delve/proc github.com/derekparker/delve/proc/test github.com/derekparker/delve/service github.com/derekparker/delve/service/api github.com/derekparker/delve/service/debugger github.com/derekparker/delve/service/rpc github.com/derekparker/delve/service/test github.com/derekparker/delve/terminal
# github.com/derekparker/delve/proc
proc/registers.go:20: undefined: registers
proc/threads_linux.go:64: undefined: Regs
# github.com/derekparker/delve/proc
proc/registers.go:20: undefined: registers
proc/threads_linux.go:64: undefined: Regs
make: *** [test] Error 2

**Comment by alanjds** [comment]
Today the error is a bit better, but still an error.

Will post their output later.

**Comment by zarelit** [comment]
As of 2023 it looks like delve is not supported on armhf by returning at build time 

```
service/debugger/debugger.go:32:2: found packages native (dump_linux.go) and your_linux_architecture_is_not_supported_by_delve (support_sentinel_linux.go) in /app/pkg/proc/native
```
and is now documented here: https://github.com/go-delve/delve/blob/master/Documentation/faq.md#-im-getting-an-error-while-compiling-delve--unsupported-architectures-and-oss

**Comment by SamB** [comment]
See also <https://github.com/go-delve/delve/issues/2051>; according to <https://github.com/go-delve/delve/issues/2051#issuecomment-2567937822> there is even working code available?
